os: linux
dist: bionic
language: shell

services:
  - docker

script:
  - docker-compose up --exit-code-from testing-env testing-env && docker-compose build java-app

deploy:
  provider: script
  script: bash docker_push
  on:
branch: master
