# Test container
FROM maven:3-jdk-8 AS testing-env
WORKDIR /app
COPY back/pom.xml .
RUN mvn dependency:go-offline -B
COPY back/src src
RUN mvn spotbugs:check && mvn spotless:apply && mvn spotless:check
ENTRYPOINT ["mvn", "clean", "test"]

