# Test container
FROM maven:3-jdk-8 AS testing-env
WORKDIR /app
COPY back/pom.xml .
RUN mvn dependency:go-offline -B
COPY back/src src
ENV DATABASE_URL //postgres:admin@postgresdb:5432/postgres
CMD ["mvn", "clean", "test"]

