version: '3.1'

services:

  postgresdb:
    image: postgres:latest
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  java-app:
    build:
      context: .
      args:
        - appversion=0.0.1-SNAPSHOT
    container_name: myApp
    restart: always
    expose:
      - 8080
    depends_on: 
      - postgresdb
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=$(heroku config:get DATABASE_URL -a rocket-ivvq-project) rocket-ivvq-project



