version: '3.1'

services:

  postgresdb:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASS: xxxxx
      POSTGRES_USER: xxxxx

  java-app:
    build: .
    depends_on: 
      - postgresdb
    ports:
      - 8080:8080


