#!/bin/bash
set -e

echo "$HEROKU_AUTH_TOKEN" | docker login -u _ --password-stdin registry.heroku.com

docker push ivvq-2020-project-rocket_java-app

docker logout

# cf. https://devcenter.heroku.com/articles/container-registry-and-runtime#api
# and https://toedter.com/2018/06/02/heroku-docker-deployment-update/
imageId=$(docker inspect ivvq-2020-project-rocket_java-app --format="{{.Id}}")
payload="{\"updates\": [{\"type\": \"web\", \"docker_image\": \"$imageId\"}]}"
curl -n -X PATCH https://api.heroku.com/apps/rocket-ivvq-project/formation \
  -d "$payload" \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
-H "Authorization: Bearer $HEROKU_AUTH_TOKEN"
